# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bfd2dd955565d5c68a7074c01f20d291abb1d4c1d595a13322de7340b259c95072f3dc08621fd013d46895d8f987650583f6b34b620267a8bbd76f2af6efeac3

test:
  secret_key_base: 787eb3c7c341b8791be613c65ce0f5d75fa5ca1714fa199d7cfcdff355b62b32f502a74e42149047cc08f707bb3955215c4965f05829f269004bdcf427d5b90b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
